import Navbar from '@/components/header/Navbar'
import './globals.css'
import Footer from '@/components/footer/Footer'


export const metadata = {
  title: 'KickShare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
